name: Airflow CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test-airflow-dag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Airflow
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Validate DAG
        run: |
          python dags/csv_etl_dag.py
